config/routes.rb
Rails.application.routes.draw do

devise_for :users
resources :users
resources :friendships
root 'pages#search'

resources :pages
resources :playlists
resources :songs

get 'search' => 'pages#search'
get 'search_results' => 'pages#search_results'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates :user_id, :friend_id, presence: true
  validate :uniquiness_of_friendship

  def uniquiness_of_friendship

    unless Friendship.where(user_id: self.user_id, friend_id: self.friend_id).empty? &&
           Friendship.where(user_id: self.friend_id, friend_id: self.user_id).empty?

      errors[:base] << ("Friendship already exists")
    end
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :added_by, :song_uri, :song_name, presence: true
  validates :song_name, uniqueness: { scope: :user_id,
  message: "song already on playlist!" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters and numbers"}
  validates :username, uniqueness: true
  validates :email, uniqueness: true
  belongs_to :song
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :create_permalink

  mount_uploader :avatar, AvatarUploader

  def to_param
    permalink
  end

  def all_friends
    friends + inverse_friends
  end

  def all_friendships
    friendships + inverse_friendships
  end

  private
    def create_permalink
      self.permalink = username
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def escaped_search
    if params[:search]
      return CGI::escape(params[:search])
    else
      return ''
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :username, :avatar]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name, :username, :avatar]
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController


  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      flash[:notice] = "#{@friendship.friend.username} added as a friend!"
      redirect_to users_path
    else
      flash[:notice] = "already friends with #{@friendship.friend.username}!"
      redirect_to users_path
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "removed friendship"
    redirect_to current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def search_spotify(search)
    search_results = HTTParty.get("http://ws.spotify.com/search/1/track.json?q=#{search}")
  end

  def homepage

  end

  def search

  end

  def search_results
    if params[:page]
      @page = params[:page].to_i
    else
      @page = 1
    end

    start = (@page - 1) * 5

    @search_query = escaped_search
    @results = search_spotify(@search_query)["tracks"][start..start + 4]
    render('search_results')
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @user = User.find_by_permalink(params[:id])
    @params_id = @user.id
    @friends = Friendship.where(user_id: @params_id)
  end

  def create

    @user_ids = params[:user_ids]
    @artist = params[:song][:name]


    if params[:user_add]
      @song = Song.create(song_uri: params[:song][:song_uri],
      song_name: params[:song][:song_name], user_id: current_user.id, added_by: current_user.username)
      redirect_to "/users/#{current_user.permalink}"
      flash[:notice] = "#{@song.song_name} added to your playlist!"
    else
      @user_ids.each do |userid|
        @song = Song.create(song_uri: params[:song][:song_uri],
        song_name: params[:song][:song_name], user_id: userid, added_by: current_user.username)
      end
      flash[:notice] = "#{@song.song_name} added to playlists!"
      # redirect_to root_path
      redirect_to("/search_results?search=#{escaped_search}")
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = "#{@song.song_name} deleted from playlist"
    redirect_to "/users/#{current_user.permalink}"
  end

  private

  def song_params
    params.require(:song).permit(:song_uri, :user_id, :song_name, :added_by)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_permalink(params[:id])
    @songs = Song.where(user:  @user)
    @friendships = @user.all_friendships
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>listenUP!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar-wrapper">
    <div class="container">
      <div class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/">listenUP!</a></li>
              <li><a href="/search">search</a></li>
              <% if user_signed_in? %>
                <li><%=link_to "my playlist", "/users/#{current_user.permalink}" %></li>
                <li><%=link_to "find friends", users_path %></li>
                <li><%=link_to "sign out", destroy_user_session_path, method: :delete %></li>
                <li><%=link_to "edit account", edit_user_registration_path %></li>
              <% else %>
                <li><%= link_to "sign in", new_user_session_path %></li>
                <li><%= link_to "sign up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
    </div>
  </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js">
    </script>
</body>
</html>

app/views/pages/search.html.erb
  <div class="jumbotron homepage">
    <h1>listenUP!</h1>
    <form action= "/search_results" method="get">
      <input type="text" name="search" class="form-control home_search" placeholder="song, artist, album..", autocomplete="off"><br>
      <p><input type= "submit" class= "btn btn-lg btn-success" value= "search!"></p>
    </form>
  </div>


  <footer>
    <p>developed by <a href="http://www.chriswfinlayson.com">
    chris finlayson</a> powered by <a href="http://www.spotify.com" class="spotify">spotify</a> </p>
  </footer>

app/views/playlists/show.html.erb
<h1 style="color: white"><%= @user.username %></h1>

<h3 style="color: white">My Playlist</h3>
<div class="container">

<% songs = [] %>
<% @songs.each do |song| %>
  <% songs << song.song_uri.gsub("spotify:track:","") %>
<% end %>
<% songs = songs.join(",") %>

<iframe src="https://embed.spotify.com/?uri=spotify:trackset:ChrisFinlayson:<%=songs%>"  width="300" height="380"frameborder="0" allowtransparency="true"></iframe>
  <table class="table search_results">
    <% @songs.each do |song| %>
    <tr>
      <td>
        <h4><%= song.song_name %></h4>
        added by: <%= song.added_by %>
      </td>
      <td>
         <%= link_to 'delete', song, :method => :delete, :class => "btn btn-lg btn-success"%>
      </td>
    </tr>
      <% end %>
  </table>
</div>

<h2>Friends</h2>
  <table style="color: white" class="table">
    <% @user.all_friends.each do |friend| %>
     <% if friend.id != @params_id %>
      <tr>
        <td>
        <%= link_to friend.username, "/playlists/#{friend.permalink}"  %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </table>
<%= link_to "Search for friends", users_path %>

app/views/users/index.html.erb
<h1 class="find_friends">find friends</h1>

<table class="table find_friends">
  <% @users.each do |user| %>
    <% if user.username != current_user.username %>
      <tr>
        <td><%= image_tag user.avatar.url(:thumb), class: "img_thumb" %>
          <%= user.first_name %> <%=user.last_name%>
        </td>
        <td>
          <%= user.username %>
        </td>
         <% if user_signed_in? %>
        <td style="text-align: right">
          <%= link_to "view playlist", "/users/#{user.username}" %> |
          <%= link_to "add friend", friendships_path(:friend_id => user.id), :method => :post %>
        </td>
          <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/users/show.html.erb
<div class="row">
      <div class="col-lg-4 col-md-4">
        <div class="playlist_image">
          <%= image_tag @user.avatar.url, class: "avatar" %>
        </div>
        <div class="user_info">
          <h1 style="color: #5cb85c"><%= @user.username %></h1>
          <%= @user.first_name %> <%= @user.last_name %>
        </div>
      </div>
  <div class="col-lg-4 col-md-4">
    <% songs = [] %>
    <% @songs.each do |song| %>
      <% songs << song.song_uri.gsub("spotify:track:","") %>
    <% end %>

    <% songs = songs.join(",") %>
      <iframe src="https://embed.spotify.com/?uri=spotify:trackset:ListenUP!:<%=songs%>"
        width="300" height="380"frameborder="0" allowtransparency="true" class="playlist_iframe">
      </iframe>
  </div>
  <div class="col-lg-4 col-md-4 div_scroll_songs dash">
    <% if @songs.count > 0 %>
      <table class="table playlist_songs">
        <% @songs.each do |song| %>
          <tr>
            <td>
              <%= song.song_name %><br>
              <div class="added_by">
                added by: <%= link_to song.added_by, "/users/#{song.added_by}" %>
              </div>
            </td>
            <td>
            <% if song.user_id == current_user.id || song.added_by == current_user.username %>
              <%= link_to 'delete', song, :method => :delete%>
            <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <% else %>
      <%= link_to "search for songs!", root_path %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 friends">
    <h2 style="color: #5cb85c">friends</h2>
    <div class="scroll_friends">
    <table class="table">
          <% @friendships.each do |friendship| %>
            <tr>
              <% if friendship.friend.username != params[:id] %>
              <td>
                <%= image_tag friendship.friend.avatar.url(:thumb), class: "img_thumb" %>
                <%= link_to friendship.friend.username, "/users/#{friendship.friend.permalink}" %>
              </td>
              <td>
                 <div class="fullname">
                  <%= friendship.friend.first_name %> <%= friendship.friend.last_name %>
                 </div>
              </td>
              <% if current_user.username == params[:id] %>
              <td>
                <div class="remove"><%= link_to "remove", friendship, method: :delete %></div>
              </td>
              <% end %>
            <% end %>

            <% if friendship.user.username != params[:id] %>
              <td>
                <%= image_tag friendship.user.avatar.url(:thumb), class: "img_thumb" %>
                <%= link_to friendship.user.username, "/users/#{friendship.user.permalink}" %>
              </td>
              <td>
                 <div class="fullname">
                  <%= friendship.user.first_name %> <%= friendship.user.last_name %>
                 </div>
              </td>
              <% if current_user.username == params[:id] %>

              <td>
                <div class="remove"><%= link_to "remove", friendship, method: :delete %></div>
              </td>
            </tr>
              <% end %>
            <% end %>
          <% end %>
        </table>
      </div>
  </div>
</div>